const translations = {
    en: {
        menu: "Menu",
        welcome_header: "Welcome to Saudi International Livestock Quarantine Center (SILQC)",
        welcome_text: "Ensuring safe and disease-free livestock trade worldwide.",
        largest_facility: "Largest Quarantine Facility in Somaliland",
        capacity: "Capacity 400,000 livestock",
        compliance: "Compliance with global biosecurity standards",
        strategic_location: "Strategic location in Berbera, Somaliland",
        exporting: "Exporting to the Middle East & Europe",
        standards: "Ensuring the highest standards in livestock health and safety.",
        read_more: "Read More",
        about_us: "About Us",
        about_welcome: "Welcome to SILQC",
        about_description: "Saudi International Livestock Quarantine Center (SILQC) is the largest livestock quarantine facility in Somaliland, covering 2 km². Strategically located in Berbera, our center ensures the safe and disease-free transport of livestock globally.",
        founded: "Founded in 2025, SILQC is a privately developed but government-regulated facility, supervised by the Ministry of Livestock and Rural Development.",
        services: "Services",
        latest_services: "Our Latest Services",
        quarantine: "Livestock Quarantine & Disease Prevention",
        research: "Research & Disease Control",
        training: "Training Programs",
        market_info: "Livestock Market Information",
        find_more: "Find out More About Our Services",
        partner: "Partner with Us for Safe & Reliable Livestock Export.",
        get_touch: "Get in Touch",
        year: "Year Experienced",
        types: "Types of Livestock",
        happy: "Happy Customers",
        total: "Total Branches",
        leading_facility: "Saudi International Livestock Quarantine Center (SILQC) is a leading livestock quarantine facility in Somaliland, ensuring safe and disease-free animal exports to global markets.",
        pages: "Pages",
        home: "Home",
        about: "About",
        services: "Services",
        facilities: "Facilities",
        export: "Export",
        contact: "Contact",
        questions: "Have a Questions?",
        berbera: "Berbera, Somaliland",
        about_us: "About us",
        about_welcome: "Welcome to SILQC",
        about_description: "Saudi International Livestock Quarantine Center (SILQC) is Somaliland's largest and most advanced livestock quarantine facility. Covering 2 km², our center is located 3 km from Berbera City, strategically positioned to facilitate seamless livestock export worldwide.",
        founded: "Founded in 2025, SILQC is a privately developed facility, regulated and supervised by the Government of Somaliland through the Ministry of Livestock and Rural Development. Our goal is to ensure disease-free, high-quality livestock exports by maintaining the highest standards in animal health and biosecurity.",
        guiding_principles: "Our Guiding Principles",
        vision: "🌍 Our Vision",
        vision_text: "To be the leading provider of livestock quarantine services in the Horn of Africa, ensuring safe and disease-free global trade.",
        mission: "🎯 Our Mission",
        mission_text: "We provide bio-secure quarantine services, protecting animal health, facilitating smooth trade, and upholding the highest welfare standards.",
        core_values: "🤝 Our Core Values",
        core_values_list: "Integrity, Excellence, Sustainability, Collaboration, Animal Welfare, Responsibility",
        service: "Service",
        our_services: "Our Services",
        livestock_quarantine: "Livestock Quarantine & Disease Prevention",
        quarantine_facility: "Our quarantine facility is designed to ensure that all exported livestock is free from infectious diseases. We follow strict biosecurity measures and conduct veterinary health screenings before export.",
        health_inspections: "Regular health inspections by certified veterinarians.",
        disease_detection: "Disease detection and prevention through laboratory testing.",
        export_compliance: "Compliance with global export health regulations.",
        research_control: "Research & Disease Control",
        research_purpose: "We conduct scientific research on livestock diseases prevalent in the Horn of Africa to:",
        prevent_outbreaks: "Identify and prevent outbreaks that could impact livestock trade.",
        health_improvement: "Improve livestock health through data-driven insights.",
        farming_strategies: "Develop strategies for sustainable livestock farming.",
        training_programs: "Training Programs",
        training_audience: "We offer short-term training for:",
        veterinarians: "Veterinarians.",
        lab_techs: "Laboratory technicians.",
        livestock_handlers: "Livestock traders and handlers.",
        training_focus: "Our training programs focus on modern quarantine procedures, disease management, and export regulations.",
        market_info: "Livestock Market Information",
        market_data: "We provide real-time livestock market data, helping traders and investors make informed decisions. Our data includes:",
        price_trends: "Price trends for different livestock types.",
        export_regulations: "Export regulations in various countries.",
        supply_demand: "Supply and demand forecasts for international markets.",
        trade_support: "Trade Support & Partnerships",
        collaboration: "We work closely with:",
        traders_header: "Traders & Investors –",
        facilitating: "Facilitating trade agreements.",
        gov_header: "Government Agencies –",
        compliance: "Ensuring compliance with livestock regulations.",
        intl_header: "International Organizations –",
        expanding: "Expanding Somaliland's livestock export market.",
        facilities: "Facilities",
        our_facilities: "Our Facilities",
        world_class: "Our World-Class Quarantine Facilities",
        quarantine_center: "Our quarantine center is equipped with state-of-the-art infrastructure to handle large-scale livestock export operations.",
        diagnostic_lab: "Diagnostic Laboratory",
        lab_point1: "Advanced testing for livestock diseases.",
        lab_point2: "Compliance with export health requirements.",
        pre_quarantine: "Pre-Quarantine Area",
        pre_quarantine_desc: "Initial health screening before livestock enters the quarantine facility.",
        quarantine_stations: "Quarantine Stations (A, B, C)",
        stations_desc: "Segregation of different livestock categories for better disease control.",
        admin_offices: "Administrative Offices",
        admin_desc: "Managing quarantine operations and trade logistics.",
        post_mortem: "Post-Mortem Room",
        post_mortem_desc: "Examination of deceased animals for research and disease control.",
        incinerator: "Incinerator",
        incinerator_desc: "Safe disposal of infectious waste to prevent contamination.",
        general_store: "General Store",
        store_desc: "Storage for quarantine-related equipment and medical supplies.",
        staff_houses: "Staff Houses & Mosque",
        staff_desc: "Comfortable accommodation and prayer space for staff and visitors.",
        dipping_hole: "Dipping Hole",
        dipping_desc: "Treatment area for external parasites and infections.",
        security_room: "Security Room",
        security_desc: "24/7 monitoring to ensure facility safety and regulatory compliance.",
        export_header: "Export",
        our_exports: "Our Exports",
        global_destinations: "Our Global Export Destinations",
        export_quality: "We export high-quality livestock to international markets, ensuring compliance with global health standards.",
        middle_east: "🌍 Middle East",
        saudi_arabia: "Saudi Arabia 🇸🇦",
        saudi_desc: "One of our largest markets for sheep, goats, cattle, and camels.",
        uae: "United Arab Emirates 🇦🇪",
        uae_desc: "Exporting high-quality livestock with strict health standards.",
        qatar: "Qatar 🇶🇦",
        qatar_desc: "Regular exports of camels, sheep, and cattle to Qatar's growing market.",
        europe: "🌍 Europe",
        germany: "Germany 🇩🇪",
        germany_desc: "Supplying high-quality livestock to meet European market demands.",
        france: "France 🇫🇷",
        france_desc: "Compliant with European biosecurity and export regulations.",
        livestock_types: "Types of Livestock We Export",
        sheep: "Sheep 🐑",
        sheep_desc: "Exported for meat & breeding.",
        cattle: "Cattle 🐄",
        cattle_desc: "High-quality cattle for dairy & meat.",
        goats: "Goats 🐐",
        goats_desc: "Certified goats for dairy & meat.",
        camels: "Camels 🐫",
        camels_desc: "Premium camels for export.",
        quality_process: "Our Quality Assurance Process",
        process_desc: "Every animal undergoes a multi-step process to ensure the highest export quality.",
        step1: "Step 1: Health Screening 🩺",
        step1_desc: "Initial veterinary checks to identify any pre-existing conditions or signs of disease.",
        step2: "Step 2: Quarantine & Monitoring ⏳",
        step2_desc: "Animals are kept under observation for a set period to ensure they remain disease-free.",
        step3: "Step 3: Laboratory Testing 🔬",
        step3_desc: "Samples are tested in our diagnostic laboratory to verify the absence of infectious diseases.",
        step4: "Step 4: Certification 📜",
        step4_desc: "Government-approved veterinarians issue health certifications for each batch of livestock.",
        step5: "Step 5: Export & Compliance ✅",
        step5_desc: "Only certified, healthy animals are approved for transport to international markets."
    },
    ar: {
        menu: "القائمة",
        welcome_header: "مرحبًا بكم في المركز السعودي الدولي للحجر البيطري (SILQC)",
        welcome_text: "ضمان تجارة آمنة وخالية من الأمراض للماشية على مستوى العالم.",
        largest_facility: "أكبر منشأة للحجر البيطري في أرض الصومال",
        capacity: "سعة 400,000 رأس ماشية",
        compliance: "الامتثال لمعايير الأمن الحيوي العالمية",
        strategic_location: "موقع استراتيجي في بربرة، أرض الصومال",
        exporting: "التصدير إلى الشرق الأوسط وأوروبا",
        standards: "ضمان أعلى المعايير في صحة وسلامة الماشية.",
        read_more: "اقرأ المزيد",
        about_us: "من نحن",
        about_welcome: "مرحبًا بكم في SILQC",
        about_description: "المركز السعودي الدولي للحجر البيطري (SILQC) هو أكبر منشأة للحجر البيطري في أرض الصومال، حيث تبلغ مساحته 2 كم². يقع المركز بشكل استراتيجي في بربرة، ويضمن نقلًا آمنًا وخاليًا من الأمراض للماشية على مستوى العالم.",
        founded: "تأسس في عام 2025، SILQC هو منشأة مطورة بشكل خاص ولكنها خاضعة للتنظيم الحكومي، وتخضع لإشراف وزارة الثروة الحيوانية والتنمية الريفية.",
        services: "الخدمات",
        latest_services: "أحدث خدماتنا",
        quarantine: "الحجر البيطري للحيوانات ومنع الأمراض",
        research: "البحث ومكافحة الأمراض",
        training: "البرامج التدريبية",
        market_info: "معلومات سوق الماشية",
        find_more: "اكتشف المزيد عن خدماتنا",
        partner: "كن شريكًا معنا لتصدير آمن وموثوق للماشية.",
        get_touch: "تواصل معنا",
        year: "سنوات الخبرة",
        types: "أنواع الماشية", 
        happy: "عملاء سعداء",
        total: "إجمالي الفروع",
        leading_facility: "المركز السعودي الدولي للحجر البيطري (SILQC) هو المنشأة الرائدة في الحجر البيطري في أرض الصومال، يضمن تصدير حيوانات آمنة وخالية من الأمراض إلى الأسواق العالمية.",
        pages: "الصفحات",
        home: "الرئيسية",
        about: "من نحن",
        services: "الخدمات",
        facilities: "المرافق",
        export: "التصدير",
        contact: "اتصل بنا",
        questions: "هل لديك أسئلة؟",
        berbera: "بربرة، أرض الصومال",
        about_us: "من نحن",
        about_welcome: "مرحبًا بكم في SILQC",
        about_description: "المركز السعودي الدولي للحجر البيطري (SILQC) هو أكبر وأكثر مرافق الحجر البيطري تطورًا في أرض الصومال. بمساحة 2 كم²، يقع مركزنا على بعد 3 كم من مدينة بربرة، في موقع استراتيجي لتسهيل تصدير الماشية بسلاسة إلى جميع أنحاء العالم.",
        founded: "تأسس SILQC في عام 2025 كمنشأة مطورة بشكل خاص، وتخضع للتنظيم والإشراف من قبل حكومة أرض الصومال عبر وزارة الثروة الحيوانية والتنمية الريفية. هدفنا هو ضمان تصدير ماشية عالية الجودة وخالية من الأمراض من خلال الحفاظ على أعلى معايير الصحة الحيوانية والأمن الحيوي.",
        guiding_principles: "مبادئنا التوجيهية",
        vision: "🌍 رؤيتنا",
        vision_text: "أن نكون المزود الرائد لخدمات الحجر البيطري للماشية في القرن الأفريقي، وضمان تجارة عالمية آمنة وخالية من الأمراض.",
        mission: "🎯 مهمتنا",
        mission_text: "نقدم خدمات حجر بيطري آمنة حيويًا، لحماية صحة الحيوانات، وتسهيل التجارة السلسة، والحفاظ على أعلى معايير الرفاهية.",
        core_values: "🤝 قيمنا الأساسية",
        core_values_list: "النزاهة، التميز، الاستدامة، التعاون، رفاهية الحيوان، المسؤولية",
        service: "الخدمة",
        our_services: "خدماتنا",
        livestock_quarantine: "الحجر البيطري للحيوانات ومنع الأمراض",
        quarantine_facility: "تم تصميم منشأة الحجر البيطري الخاصة بنا لضمان خلو جميع الماشية المصدرة من الأمراض المعدية. نتبع إجراءات صارمة للأمن الحيوي ونقوم بإجراء فحوصات صحية بيطرية قبل التصدير.",
        health_inspections: "فحوصات صحية دورية بواسطة أطباء بيطريين معتمدين.",
        disease_detection: "الكشف عن الأمراض والوقاية منها عبر الفحوصات المخبرية.",
        export_compliance: "الامتثال للوائح الصحية العالمية للتصدير.",
        research_control: "البحث ومكافحة الأمراض",
        research_purpose: "نقوم بإجراء أبحاث علمية حول أمراض الماشية المنتشرة في القرن الأفريقي من أجل:",
        prevent_outbreaks: "تحديد ومنع تفشي الأمراض التي قد تؤثر على تجارة الماشية.",
        health_improvement: "تحسين صحة الماشية من خلال الرؤى القائمة على البيانات.",
        farming_strategies: "تطوير استراتيجيات لتربية الماشية المستدامة.",
        training_programs: "البرامج التدريبية",
        training_audience: "نقدم تدريبات قصيرة المدى ل:",
        veterinarians: "الأطباء البيطريين.",
        lab_techs: "فنيي المختبرات.",
        livestock_handlers: "تجار ومناولي الماشية.",
        training_focus: "تركز برامجنا التدريبية على إجراءات الحجر البيطري الحديثة، وإدارة الأمراض، واللوائح التصديرية.",
        market_info: "معلومات سوق الماشية",
        market_data: "نوفر بيانات سوق الماشية في الوقت الحقيقي لمساعدة التجار والمستثمرين على اتخاذ قرارات مستنيرة. تشمل بياناتنا:",
        price_trends: "اتجاهات الأسعار لأنواع الماشية المختلفة.",
        export_regulations: "لوائح التصدير في مختلف البلدان.",
        supply_demand: "توقعات العرض والطلب في الأسواق الدولية.",
        trade_support: "الدعم التجاري والشراكات",
        collaboration: "نعمل عن كثب مع:",
        traders_header: "التجار والمستثمرون –",
        facilitating: "تيسير الاتفاقيات التجارية.",
        gov_header: "الوكالات الحكومية –",
        compliance: "ضمان الامتثال للوائح الماشية.",
        intl_header: "المنظمات الدولية –",
        expanding: "توسيع سوق تصدير ماشية أرض الصومال.",
        facilities: "المرافق",
        our_facilities: "مرافقنا",
        world_class: "مرافق الحجر البيطري العالمية لدينا",
        quarantine_center: "مركز الحجر البيطري لدينا مجهز ببنية تحتية حديثة للتعامل مع عمليات تصدير الماشية على نطاق واسع.",
        diagnostic_lab: "المختبر التشخيصي",
        lab_point1: "اختبارات متقدمة لأمراض الماشية.",
        lab_point2: "الامتثال لمتطلبات الصحة التصديرية.",
        pre_quarantine: "منطقة ما قبل الحجر البيطري",
        pre_quarantine_desc: "الفحص الصحي الأولي قبل دخول الماشية إلى منشأة الحجر البيطري.",
        quarantine_stations: "محطات الحجر البيطري (أ، ب، ج)",
        stations_desc: "عزل الفئات المختلفة من الماشية لتحسين السيطرة على الأمراض.",
        admin_offices: "المكاتب الإدارية",
        admin_desc: "إدارة عمليات الحجر البيطري واللوجستيات التجارية.",
        post_mortem: "غرفة التشريح",
        post_mortem_desc: "فحص الحيوانات النافقة لأغراض البحث ومكافحة الأمراض.",
        incinerator: "المحرقة",
        incinerator_desc: "التخلص الآمن من النفايات المعدية لمنع التلوث.",
        general_store: "المستودع العام",
        store_desc: "تخزين المعدات اللازمة للحجر البيطري والإمدادات الطبية.",
        staff_houses: "مساكن الموظفين والمسجد",
        staff_desc: "سكن مريح ومساحة للصلاة للموظفين والزوار.",
        dipping_hole: "حفرة التغطيس",
        dipping_desc: "منطقة معالجة الطفيليات الخارجية والالتهابات.",
        security_room: "غرفة الأمن",
        security_desc: "مراقبة على مدار الساعة لضمان سلامة المنشأة والامتثال التنظيمي.",
        export_header: "التصدير",
        our_exports: "صادراتنا",
        global_destinations: "وجهاتنا التصديرية العالمية",
        export_quality: "نصدر ماشية عالية الجودة إلى الأسواق الدولية مع ضمان الامتثال لمعايير الصحة العالمية.",
        middle_east: "🌍 الشرق الأوسط",
        saudi_arabia: "المملكة العربية السعودية 🇸🇦",
        saudi_desc: "أحد أكبر أسواقنا للأغنام والماعز والأبقار والإبل.",
        uae: "الإمارات العربية المتحدة 🇦🇪",
        uae_desc: "تصدير ماشية عالية الجودة مع معايير صحية صارمة.",
        qatar: "قطر 🇶🇦",
        qatar_desc: "صادرات منتظمة من الإبل والأغنام والأبقار إلى السوق القطري المتنامي.",
        europe: "🌍 أوروبا",
        germany: "ألمانيا 🇩🇪",
        germany_desc: "تزويد الأسواق الأوروبية بماشية عالية الجودة.",
        france: "فرنسا 🇫🇷",
        france_desc: "ممتثلون لمعايير الأمن الحيوي واللوائح التصديرية الأوروبية.",
        livestock_types: "أنواع الماشية التي نصدرها",
        sheep: "الأغنام 🐑",
        sheep_desc: "مصدّرة لأغراض اللحوم والتكاثر.",
        cattle: "الأبقار 🐄",
        cattle_desc: "أبقار عالية الجودة لمنتجات الألبان واللحوم.",
        goats: "الماعز 🐐",
        goats_desc: "ماعز معتمدة لمنتجات الألبان واللحوم.",
        camels: "الإبل 🐫",
        camels_desc: "إبل ممتازة للتصدير.",
        quality_process: "عملية ضمان الجودة",
        process_desc: "تمر كل حيوان بخطوات متعددة لضمان أعلى معايير الجودة التصديرية.",
        step1: "الخطوة 1: الفحص الصحي 🩺",
        step1_desc: "فحوصات بيطرية أولية للكشف عن أي أمراض موجودة مسبقًا.",
        step2: "الخطوة 2: الحجر البيطري والمراقبة ⏳",
        step2_desc: "مراقبة الحيوانات لفترة محددة لضمان خلوها من الأمراض.",
        step3: "الخطوة 3: الفحوصات المخبرية 🔬",
        step3_desc: "اختبار العينات في مختبراتنا التشخيصية للتأكد من عدم وجود أمراض معدية.",
        step4: "الخطوة 4: التصديق 📜",
        step4_desc: "إصدار شهادات صحية معتمدة من الحكومة لكل دفعة من الماشية.",
        step5: "الخطوة 5: التصدير والامتثال ✅",
        step5_desc: "يتم تصدير الحيوانات المعتمدة والخالية من الأمراض فقط إلى الأسواق الدولية.",
    }
};

function switchLanguage(lang) {
    document.querySelectorAll('[data-key]').forEach(element => {
        const key = element.getAttribute('data-key');
        element.textContent = translations[lang][key] || translations['en'][key] || key;

        // Apply direction only to text elements
        element.style.direction = lang === 'ar' ? 'rtl' : 'ltr';
        element.style.textAlign = lang === 'ar' ? 'right' : '';
    });

    // Update the lang attribute but NOT the global direction
    document.documentElement.setAttribute('lang', lang);

    // Store preference
    localStorage.setItem('lang', lang);
}

document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('lang') || 'en';
    document.documentElement.setAttribute('lang', savedLang);
    switchLanguage(savedLang);
});
